#/bin/bash
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{Authenticator_allowed_users}/${Authenticator_allowed_users}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{Authenticator_admin_users}/${Authenticator_admin_users}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{JupyterHub_spawner_class}/${JupyterHub_spawner_class}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_image}/${KubeSpawner_image}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_pod_name_template}/${KubeSpawner_pod_name_template}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_cpu_guarantee}/${KubeSpawner_cpu_guarantee}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_cpu_limit}/${KubeSpawner_cpu_limit}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_mem_guarantee}/${KubeSpawner_mem_guarantee}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_mem_limit}/${KubeSpawner_mem_limit}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_env_keep}/${KubeSpawner_env_keep}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_environment}/${KubeSpawner_environment}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_namespace}/${KubeSpawner_namespace}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_node_selector}/${KubeSpawner_node_selector}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_tolerations}/${KubeSpawner_tolerations}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_service_account}/${KubeSpawner_service_account}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_volume_mounts}/${KubeSpawner_volume_mounts}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_volumes}/${KubeSpawner_volumes}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_notebook_dir}/${KubeSpawner_notebook_dir}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_working_dir}/${KubeSpawner_working_dir}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_args}/${KubeSpawner_args}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_http_timeout}/${KubeSpawner_http_timeout}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_start_timeout}/${KubeSpawner_start_timeout}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{KubeSpawner_hub_connect_url}/${KubeSpawner_hub_connect_url}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{LocalAuthenticator_create_system_users}/${LocalAuthenticator_create_system_users}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{JupyterHub_authenticator_class}/${JupyterHub_authenticator_class}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{NativeAuthenticator_open_signup}/${NativeAuthenticator_open_signup}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{NativeAuthenticator_minimum_password_length}/${NativeAuthenticator_minimum_password_length}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{NativeAuthenticator_check_common_password}/${NativeAuthenticator_check_common_password}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{NativeAuthenticator_allowed_failed_logins}/${NativeAuthenticator_allowed_failed_logins}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{NativeAuthenticator_seconds_before_next_try}/${NativeAuthenticator_seconds_before_next_try}/g" {}
find /srv/jupyterhub/jupyterhub_config.py | xargs -i sed -i "s/{JupyterHub_shutdown_on_logout}/${JupyterHub_shutdown_on_logout}/g" {}
